services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks: microservices-net
    environment: SPRING_PROFILES_ACTIVE=docker
  order:
    build: ./order-service
    container_name: order
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    networks: microservices-net
    environment: SPRING_PROFILES_ACTIVE=docker
  product:
    build: ./product-service
    container_name: product
    ports:
      - "8081:8081"
    depends-on:
      - discovery-service
    networks: microservices-net
    environment: SPRING_PROFILES_ACTIVE=docker
networks:
  microservices-net:
    driver: bridge