server:
  port: 8083
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service # lb: saved in Eureka
          predicates:
            - Path=/users/**
          filters:
            - AddRequestHeader=Content-Type, application/json

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - AddRequestHeader=Content-Type, application/json

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - AddRequestHeader=Content-Type, application/json
management: #actuator to see all routes active
  endpoints:
    web:
      exposure:
        include: "gateway,health,info,metrics"
eureka:
  client:
    service-url:
      defaultZone: "http://eureka:password@discovery-service:8762/eureka"
