server:
  port: 8080
spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: "http://eureka:password@discovery-service:8761/eureka"