spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Use 'update', 'validate', 'create', or 'create-drop' as needed
    show-sql: true
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: "http://eureka:password@discovery-service:8762/eureka"
