spring:
  application:
    name: discovery-service
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_USERNAME:password}