spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: "http://eureka:password@discovery-service:8761/eureka"
