server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service # lb: saved in Eureka
          predicates:
            - Path=/users/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
management: #actuator to see all routes active
  endpoints:
    web:
      exposure:
        include: "gateway,health,info,metrics"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
