name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 #is a built-in action from GitHub.

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven  # Remplace par "gradle" si ton projet utilise Gradle

      - name: Build with Maven
        run: mvn clean install -DskipTests=true  # Remplace par "gradle build" si Gradle

      - name: Run Tests
        run: mvn test

  #deploy:
  #  name: Deploy to Server
  #  needs: build
  #  runs-on: ubuntu-latest
  #  if: github.ref == 'refs/heads/master'

  #  steps:
  #    - name: Deploy to server
  #      run: |
  #        echo "Connexion au serveur et déploiement..."
  #        # Exemple de déploiement via SSH (remplace par ton propre script)
  #        ssh user@server 'cd /chemin/projet && git pull && mvn clean install && systemctl restart mon-app'
